### ISSUE TITLE
I can not install this package in my application

### ISSUE THREAD

**Issue by khacluan** [lukevella/react-activity#3]
Currently, I used react@15.3.0, and when I install this package, it doesn't work.

```error
451 verbose targetResolver reading package data from /Users/macstore1/projects/lixibox/client/node_modules/.bin/webpack/package.json
452 verbose already installed skipping react-dom@^0.14.3 /Users/macstore1/projects/lixibox/client
453 verbose already installed skipping react@^0.14.3 /Users/macstore1/projects/lixibox/client
454 silly install resolved []
455 verbose unlock done using /Users/macstore1/.npm/_locks/react-activity-da0841a5e93a897c.lock for /Users/macstore1/projects/lixibox/client/node_modules/react-activity
456 verbose validateInstall loading /Users/macstore1/projects/lixibox/client/package.json for validation
457 verbose stack Error: The package react@15.3.0 does not satisfy its siblings' peerDependencies requirements!
457 verbose stack     at /Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/lib/install.js:125:32
457 verbose stack     at /Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/lib/install.js:268:7
457 verbose stack     at /Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
457 verbose stack     at /Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
457 verbose stack     at cb (/Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
457 verbose stack     at /Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
457 verbose stack     at cb (/Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
457 verbose stack     at /Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
457 verbose stack     at cb (/Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
457 verbose stack     at /Users/macstore1/.nvm/versions/node/v0.12.13/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
458 verbose cwd /Users/macstore1/projects/lixibox/client
459 error Darwin 14.5.0
460 error argv "/Users/macstore1/.nvm/versions/node/v0.12.13/bin/node" "/Users/macstore1/.nvm/versions/node/v0.12.13/bin/npm" "install" "react-activity@1.0.14" "--save"
461 error node v0.12.13
462 error npm  v2.15.0
463 error code EPEERINVALID
464 error peerinvalid The package react@15.3.0 does not satisfy its siblings' peerDependencies requirements!
464 error peerinvalid Peer react-bootstrap@0.30.1 wants react@>=0.14.0
464 error peerinvalid Peer react-dnd@2.1.4 wants react@^0.14.0 || ^15.0.0-0
464 error peerinvalid Peer react-dom@15.3.0 wants react@^15.3.0
464 error peerinvalid Peer react-on-rails@6.0.5 wants react@>= 0.14
464 error peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
464 error peerinvalid Peer react-router@2.6.1 wants react@^0.14.0 || ^15.0.0
464 error peerinvalid Peer react-activity@1.0.14 wants react@^0.14.3
465 verbose exit [ 1, true ]
```

**Comment by lukevella** [comment]
The peer dependency version has been update and should fix this issue. Sorry for the delay.
